package com.naijatravelshop.persistence.model.enums;

public enum ServiceTaskSubject {

    REFUND("REFUND"),
    PAYMENT_CONFIRMATION("PAYMENT CONFIRMATION"),
    FLIGHT_ENQUIRY("FLIGHT ENQUIRY"),
    HOTEL_ENQUIRY("HOTEL ENQUIRY"),
    VISA("VISA"),
    TICKETING("TICKETING"),
    PACKAGES("PACKAGES"),
    INSURANCE("INSURANCE"),
    GENERAL_ENQUIRY("GENERAL ENQUIRY"),
    BOOKING_CONFIRMATION("BOOKING CONFIRMATION"),
    FLIGHT_FARE_CHANGE("FLIGHT FARE CHANGE"),
    FLIGHT_ETICKET_NOT_FOUND("FLIGHT E-TICKET NOT FOUND"),
    VOUCHER_NOT_FOUND("VOUCHER NOT FOUND"),
    FLIGHT_CANCELLATION("FLIGHT CANCELLATION"),
    FLIGHT_DATE_CHANGE("FLIGHT DATE CHANGE"),
    CARD_PAYMENT_FAILED("CARD PAYMENT FAILED"),
    FLIGHT_WEIGHT_LIMIT("FLIGHT WEIGHT LIMIT"),
    TRANSFER_REQUEST("TRANSFER REQUEST"),
    HOTEL_CANCELLATION_PENALTY("HOTEL CANCELLATION PENALTY"),
    HOTEL_DATE_CHANGE("HOTEL DATE CHANGE"),
    OTHERS("OTHERS");

    private final String value;

    ServiceTaskSubject(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
